index = {
    'texto_head': '',
    'texto_footer': ''
}

categorias = [
    {
        'nombre': 'Juguetes y juegos',
        'descripcion': 'En nuestra sección de juguetes y juegos Vintage, tendrás la oportunidad de disfrutar las maravillas del entretenimiento infantil de años atrás. Sentirás añoranza de tu niñez al contemplar consolas de juegos, juguetes de cuerda, juegos de mesas, proyectores y muchos otros artículos de juguetería que disfrutaste en tu infancia.',
        'texto_seo': 'No quedan dudas de que los juguetes Vintage fueron diseñados con una calidad superior a la que poseen una buena parte de los juguetes actuales. Esto además de apreciarse en sus diseños y confortabilidad, también se pone de manifiesto en el hecho de que en su mayoría pueden ser reparables. Algo que difícilmente pueda ocurrir con los diseños actuales suministrados por las jugueterías. Por otra parte, un factor importante que se desprenden de los juguetes y juegos Vintage, es el valor sentimental que éstos encierran. Poseerlos te harán recordar esa época en que fuiste más feliz. Una oportunidad para volver en el tiempo y escapar del estrés de la vida actual. Auxíliate de nuestra tienda de artículos Vintage para comprar aquellos juguetes con los que tanto te regocijaste. Enséñales su valor a tus hijos, y vive nuevamente tu experiencia a través de ellos. ¿Ya estás listo para empezar?',
        'descripcion_breve': 'Adquiere aquellos juguetes Vintage con los que tanto reíste. Llévate a casa un pedazo de tu niñez.',
    },
    {
        'nombre': 'Hogar y cocina',
        'descripcion': '¿Existe algún sitio más especial que tu hogar? ¡Seguramente no!, y por eso en nuestra tienda de productos Vintage te dedicamos la categoría de hogar y cocina.  Así que, si pretendes dar un toque retro al rinconcito de tus días, nuestra tienda de artículos Vintage guarda para ti interesantes opciones.',
        'texto_seo': 'El hogar es el lugar sagrado en el cual pasamos la mayor parte del día, y si a ello le sumamos que es fiel testigo de gran parte de nuestra vida, no quedan dudas de que es un sitio al que siempre debemos consentir. ¿Por qué no decorarlo con artículos Vintage? Decorar tu morada con nuestros productos Vintage dará a tu hogar un increíble toque de elegancia. Arrastrarás el pasado a tu presente, pudiendo así, combinar lo retro con lo moderno. La mezcla perfecta para no olvidar, y vivir con los pies bien puestos sobre la tierra. Una experiencia singular que no deberías negarte. Has que tu hogar luzca como nunca, decóralo al estilo Vintage y presume de sus interesantes reliquias. ¡Recuerda que lo Vintage siempre estará de moda!',
        'descripcion_breve': 'Arrastra lo clásico hacia tu hogar y combina en él lo retro con lo moderno. Aprende a disfrutar del presente rodeándote de objetos del pasado.',
    },
    {
        'nombre': 'Relojes',
        'descripcion': '¿Quieres comprar algo especial? o ¿Buscas un regalo exclusivo? …Entonces decídete por nuestros relojes Vintage. Las inimaginables reliquias que harán que al mirar la hora sientas que viajas en el tiempo. Obséquiate u obséquiale a alguien más, la oportunidad de lucir como un aristócrata en pleno siglo XXI.',
        'texto_seo': 'Por si aún no lo sabías, es hora de que sepas que los relojes Vintage están de moda. Cada día son más asediados por el público, ya sea para lucirlos, coleccionarlos o utilizarlos como inversión. Tanto así, que gigantes de la relojería como Rolex, contemplan entre sus novedades actuales reediciones de décadas anteriores y nuevos modelos al estilo Vintage. Un ejemplo de la furia Vintage en materia de relojería, fue sin dudas cuando Ryan Gossling acudió a la gala de los Globos de Oros luciendo en su muñeca un Rolex de 1940. Un hecho que provocó que en los meses posteriores los precios de relojes Vintage se dispararan. Nuestra tienda de productos Vintage cuenta con hermosas joyas de la relojería de antaño. La oportunidad para hacer un regalo exclusivo o para obsequiarte tú mismo un regalo singular. ¡No olvides utiliza el TIEMPO a tu favor!',
        'descripcion_breve': 'Disfruta las joyas de la relojería de antaño. Adorna tu muñeca con una reliquia Vintage y presume con razón.',
    },
    {
        'nombre': 'Ropa y Accesorios',
        'descripcion': 'Si te gusta la honda retro llegó el momento que tanto esperabas. Hoy nuestra tienda de artículos Vintage cuenta con un stock de ropa y accesorios para los gustos más exquisitos. No importa cuán exigente seas, si te gusta lo clásico, nuestra ropas y accesorios Vintage están hechos para ti.',
        'texto_seo': 'Lucir la moda Vintage no solo contempla el valor de vestir atuendos y accesorios de épocas pasadas. En su esencia también se encierra la exclusividad de las prendas que, en su gran mayoría, fueron fabricadas de forma artesanal y en pequeñas cantidades. Cuando vistes un look Vintage también tienes la oportunidad de presumir finos diseños, entre los que sobresalen el encaje, el tejido, las flores, y otros detalles que son tratados de emular en las tendencias actuales debido a su originalidad. En fin, en nuestra tienda de artículos Vintage encontrarás todas las alternativas a tus gustos. Podrás escoger entre ropas y accesorios Vintage que además de su gran belleza, han logrado traspasar la frontera del tiempo gracias a su excelente calidad. ¡Recuerda que vestir Vintage es vestir exclusivo!',
        'descripcion_breve': 'Viste a lo retro y presume tu exclusividad. Utiliza nuestras ropas y accesorios Vintage para lucir sensacional.',
    },
    {
        'nombre': 'Iluminación',
        'descripcion': 'Si buscas darle luz a tu vida has llegado a la sección indicada. Aquí encontrarás elegantes y atractivas luminarias Vintage que darán brillo a tus días de manera espectacular. Escoge entre lámparas de techo, candelabros, lámparas de mesa y otras fantásticas alternativas de iluminación Vintage.',
        'texto_seo': 'A pesar del boom de los diseños actuales de luminarias, y todo el esplendor alcanzado por la revolución LED, la decoración con lámparas Vintage nunca perderá su atractivo. Emplear el decorado Vintage de luminarias permite ambientar espacios en los cuales se pueda disfrutar una apariencia bohemia, en donde lo retro toma protagonismo. Una tendencia cada día más utilizada en restaurantes, bares, salones de hoteles, hogares, y otros lugares que ostentan la elegancia ofrecida por el diseño de las luminarias Vintage. A diferencias de las luces LED, las lámparas Vintage proporcionan un ambiente cálido y glamuroso en cualquier espacio. La oportunidad para disfrutar de una atmosfera agradable, en la que podamos pasar largas horas de manera especial. ¡No lo pienses más!... Revisa nuestro stock de luminarias Vintage y diseña tu espacio especial con nuestras lámparas retro.',
        'descripcion_breve': 'Diseña un espacio especial donde primen lo retro y lo bohemio. Incluye en tu decorado las elegantes iluminarias Vintage.',
    },
    {
        'nombre': 'Grandes electrodomésticos',
        'descripcion': 'Quienes cuentan con más de cuatro décadas de existencia saben a ciencia cierta la calidad que ostentaban los electrodomésticos de antaño. Pensando en ellos nuestra tienda de productos Vintage ofrece una sección para los grandes electrodomésticos. La categoría en donde se agrupan algunas de estas joyas de la electrónica del hogar',
        'texto_seo': 'Durante toda la historia de los artilugios electrónicos para el hogar, han sido los fabricados durante décadas anteriores los que ha conseguido ofrecer la mejor confortabilidad. Esa es la razón por la que muchos de estos electrodomésticos Vintage se conservan en excelentes condiciones y ofrecen todavía sus originales prestaciones. Los frágiles materiales utilizados en las fabricaciones actuales y la puesta en vigor de la obsolescencia programada, han provocado que estos viejos electrodomésticos brillen por su calidad y durabilidad. Aunque parezca increíble sus capacidades técnicas pasan por encima de las más novedosas tecnologías. Por tanto, si llevas uno de nuestros electrodomésticos Vintage, también estarás llevando a tu hogar un artículo invaluable. Nuestra tienda de productos Vintage te brinda la oportunidad de hacer una adquisición duradera. Lleva a tu casa uno de nuestros electrodomésticos y disfruta de una verdadera joya de ingeniería. ¡No demores!',
        'descripcion_breve': 'Lleva a tu hogar uno de nuestros electrodomésticos Vintage. Disfruta la confortabilidad de los grandes electrodomésticos de antes.',
    },
    {
        'nombre': 'Joyería',
        'descripcion': 'Si es joyería lo que andabas buscando, aquí tenemos para todos los gustos. En nuestra tienda de artículos Vintage puedes comprar hermosos accesorios de joyería. Acceder a diseños exquisitos que años atrás fueron todo un éxito. Ya sea para ti, como para el regalo que quieres realizar, nuestros accesorios Vintage de joyería satisfarán las más grandes exigencias.',
        'texto_seo': 'La principal razón para comprar joyería Vintage radica en la singularidad de sus diseños. Fabricadas artesanalmente y en cantidades muy limitadas, estos accesorios se han convertido en reliquias exclusivas. Son ideales para lucir de manera elegante, y una de las opciones más utilizadas para un regalo especial. Ya sea como recuerdo, para regalo de cumpleaños o el aniversario de boda, la joyería Vintage sigue formando parte de las mejores alternativas. La joyería Vintage ofrece la versatilidad de lucir con cualquier corriente de moda. Por tanto, no hay que preocuparse mucho por el atuendo utilizado. Estos accesorios se las ingenian para hacerte notar siempre a la moda. De forma elegante o casual, estarán ahí para mostrar su atractivo y resaltar la imagen de quien los porta. No olvides que nuestro stock de joyería Vintage espera por ti. ¿Ya escogiste?',
        'descripcion_breve': 'Compra el regalo singular que tanto buscas. Adquiere joyería Vintage para adornar tu vida o la de alguien más.',
    },
    {
        'nombre': 'Bricolaje y herramientas',
        'descripcion': '¿Recuerdas aquellos objetos que creciste viento en casa de tus abuelos? ... Hoy tendrás la oportunidad de llevarte a casa muchos de ellos. Nuestra sección de Bricolaje y Herramientas Vintage te espera con mucho de los útiles que conociste en tu infancia. Lleva contigo objetos especiales que te harán retornar a tu infancia.',
        'texto_seo': 'Los objetos Vintage de la sección de Bricolaje y Herramientas de nuestra tienda te reservan un momento especial. Entre ellos podrás distinguir aquellas cosas que creciste viendo durante tu infancia y que nunca más has vuelto a encontrar. Te asombrarás al ver en el excelente estado que se conservan tiradores de cerámica, ventiladores, útiles de grifería, portarrollos, pomos de puerta y muchos otros objetos del pasado. En nuestra sección de bricolaje y herramientas te ofrecemos artículos Vintage que difícilmente consigas en otras partes. Además de todo, nuestros accesorios son completamente funcionales, por lo que podrás darles la utilidad que necesitas. ¿Qué mejor compañía que un pedazo del pasado? No renuncies a la nostalgia del recuerdo, lleva contigo esos productos Vintage que años atrás fueron tus preferidos',
        'descripcion_breve': 'Incluye en tu casa artículos Vintage de bricolaje y herramientas. Vive la vida presente disfrutando sensaciones del pasado.',
    },
    {
        'nombre': 'Electrónica e informática',
        'descripcion': '¿Qué causa más nostalgia que una radio, una grabadora de cassette, un teléfono o un tocadiscos de hace varias décadas atrás? En esta categoría de artículos vintage de electrónica, clasificamos para ti varios productos que te van a encantar. Algunos con lo mejor de ambos mundos, un estilo totalmente vintage con las funcionalidades de productos de electrónica modernos... echa un vistazo y compruébalo por ti mismo.',
        'texto_seo': 'El hecho de que pasados los años aún existan artículos de electrónica e informática que se conservan de manera espectacular, es un mérito que no podemos negar. En ese sentido, los artículos Vintage de electrónica e informática se vuelven objetos coleccionables y de un valor singular. Sin olvidar que la mayoría de estos artículos son funcionales, una atracción para quienes también desean darles uso y poder disfrutar de sus prestaciones. Por otra parte, es innegable la distinción y elegancia que irradian estos objetos por sí solos. Un ejemplo clásico de ello son los teléfonos Vintage, los cuales en su mayoría son utilizados de forma ornamental, debido a sus atractivos y singulares diseños. En nuestra tienda de productos Vintage encontrarás artículos de electrónica e informática interesantes. No pierdas la oportunidad de escuchar un disco de vinilo o de lucir en tu hogar un teléfono retro. ¡Esperamos por ti!',
        'descripcion_breve': 'Disfruta las prestaciones de artículos de electrónica e informática Vintage. Colecciona o luce en tu hogar objetos electrónicos que han traspasado la barrera del tiempo.',
    },
    {
        'nombre': 'Deportes y aire libre',
        'descripcion': '¿Quieres lucir verdaderamente sexy durante tu rutina de ejercicios? …Entonces esta es la oportunidad de tu vida. Llegó el momento de que escoja entre nuestros artículos deportivos Vintage los accesorios que te harán lucir irresistible. En esta sección podrás encontrar artículos deportivos que hace algunos años atrás fueron considerados extraordinarios.',
        'texto_seo': 'Una rutina de ejercicios saludable es vital para el cuidado de nuestra salud, pero… ¿Qué pasa si a ésta le sumamos una imagen seductora? Los artículos y accesorios deportivos Vintage de nuestra sección de deportes y aire libre, además de permitirte adquirir las indumentarias para lucir una honda retro durante tus entrenamientos, también te darán la oportunidad de utilizar en tus rutinas deportivas instrumentos semejantes a los utilizados por grandes deportistas de la historia. Nuestra tienda de productos Vintage te da la oportunidad de sentir en carne propia la experiencia de figuras de la historia deportiva, y a la vez, de lucir un estilo retro durante tus rutinas de entrenamiento. En nuestra sección podrás encontrar peras de boxeo, gorras, sombreros y otras indumentarias que años atrás fueron consideradas el último grito en materia deportiva. ¿Qué esperas para tu entrenamiento?',
        'descripcion_breve': 'Descubre los sensacionales accesorios deportivos de años atrás. Compra artículos deportivos Vintage para tus rutinas de entrenamiento.',
    },
    {
        'nombre': 'Oficina y papelería',
        'descripcion': 'Si eres de aquellos que aman adornar el escritorio de su casa u oficina con artículos singulares, estamos listos para satisfacer tus expectativas. Nuestra sección Vintage de oficina y papelería cuenta con accesorios retro, que podrás utilizar o presumir sobre tu mesa de trabajo. Escoge entre cuadernos de diarios, mini sobres, bolígrafos, libretas y otros.',
        'texto_seo': 'A pesar de que te resulte poco atractivo el hecho de comprar productos de oficina y papelería Vintage, existen muchas razones para hacerlo. ¿Has pensado cómo luciría tu escritorio con un accesorio del pasado? o ¿Qué imagen proyectarías al firmar con un bolígrafo antiguo? Exacto, muy lejos de parecer arcaico, al utilizar accesorios de oficina Vintage estarás demostrando cuánto amor profesas por la actividad que realizas, y lo mucho que significa para ti el pasado en tu presente. Serán más de uno los que elogien la reliquia Vintage que presumes, y es muy posible que al igual que tú terminen comprando algo parecido. Nuestra tienda de artículos Vintage pone a tu disposición productos de oficina y papelería que te serán de gran utilidad. ¡Invítalos a que formen parte de tu vida!',
        'descripcion_breve': 'Dale la utilidad que merecen o presume en tu despacho nuestros productos Vintage de oficina y papelería.',
    },
    {
        'nombre': 'Belleza',
        'descripcion': '¿Te gusta el look de Marilyn Monroe o María Félix?, Entonces llegaste a la categoría indicada. En nuestro stock Vintage de belleza, encontrarás artículos que resaltarán tu hermosura y te harán lucir como toda una estrella. La oportunidad para verte retro y elegante a la vez.',
        'texto_seo': 'Lucir bella es una prioridad para la gran mayoría de las mujeres, pero cuando se trata de belleza Vintage, ocurre algo especial. Se combinan las tendencias del pasado con la moda del presente. La honda retro es una tendencia cada vez más utilizada, y nuestra tienda Vintageame la reserva especialmente para ti. La belleza Vintage rompe con todos los estereotipos actuales de belleza. Una opción para brillar como las estrellas de años anteriores o recordar con alegre nostalgia el look de nuestras madres o abuelitas. ¿Qué otra cosa podrías exigir? En nuestra tienda de artículos Vintage lo mismo encontrarás bellos accesorios para tu cabello, que frascos con las fragancias más exquisitas de antaño. No hay dudas de que tan solo existe una cosa más hermosa que la belleza, y esa es, la belleza Vintage.',
        'descripcion_breve': 'Resalta tu belleza y luce un look sorprendente con atractivos accesorios Vintage. Arrastra la belleza del pasado a la moda del presente.',
    },
    {
        'nombre': 'Instrumentos musicales',
        'descripcion': 'Si eres seguidor de John Lennon, Queen, George Michael u otro músico de décadas atrás, nuestro portal de productos Vintage te da la oportunidad de que lleves un pedacito de su época a casa. Lleva contigo artículos o accesorios musicales semejantes a los utilizados por estrellas de la música del pasado.',
        'texto_seo': 'Las décadas pasadas fueron proliferas en talentosas estrellas musicales. En sus entrañas se gestaron figuras tan exitosas como Elton John, Michael Bolton, Madonna, Michael Jackson, y surgieron agrupaciones tan famosas como Europe, Roxette y Queen. Toda una colección de prodigios musicales que retumbaron y siguen retumbando entre sus aficionados. En nuestra sección de instrumentos musicales Vintage podrás adquirir muchos de los accesorios de música utilizados durante décadas anteriores. Una oportunidad para poder conectar con el tiempo de tus grandes estrellas musicales, y apreciar la valía de instrumentos y accesorios que marcaron época. Accede a nuestra tienda de productos Vintage y no olvides llevar contigo un pedazo de la historia de la música. Regálate la oportunidad de traer una parte del pasado musical y guardarlo muy cerca de ti.',
        'descripcion_breve': 'Atrévete a comprar instrumentos y accesorios de música de décadas prodigiosas. Aprovecha nuestros artículos musicales Vintage y llévate un recuerdo especial.',
    },
    {
        'nombre': 'Jardín',
        'descripcion': 'Nuestra tienda de productos Vintage también destina una sección a los viejos accesorios de jardinería. Aquí podrás encontrarás artículos tan necesarios como botellas de riego, cajas de manzanas, cubos de hierro, y un sin número de útiles Vintage de jardinería que podrías reutilizar en el cuidado de tu jardín.',
        'texto_seo': 'Para los amantes del cuidado del jardín nuestra tienda de artículos Vintage ofrece valiosos útiles de jardinería. Tendrás la oportunidad de trabajar tu huerto o jardín utilizando accesorios antiguos, y por tanto, podrás poner en práctica métodos de horticultura mucho más naturales a los utilizados en la actualidad. La otra parte positiva de comprar nuestros productos Vintage de jardinería reside en la baja cuantía de sus precios. La jardinería se ha convertido en una actividad costosa y su práctica exige de gastos que en ocasiones no son convenientes asumir. Si buscas entre nuestros productos encontrarás precios asequibles, y podrás llevarte a casa accesorios verdaderamente útiles. Cuida tu jardín de forma natural y saca provecho de nuestros sorprendentes artículos Vintage de jardinería. Transforma el cuidado del jardín de tu casa en la actividad más esperada de tu día.',
        'descripcion_breve': 'Compra accesorios Vintage para el cuidado de tu jardín. Disfruta la practica de la jardinería con los útiles de décadas pasadas',
    },
    {
        'nombre': 'Coche y moto',
        'descripcion': 'Los accesorios retro de coches y motos también forman parte del stock de nuestra tienda de artículos Vintage. Aquí encontrarás artículos para lucir en tu viaje, y también para decorar al estilo Vintage el auto o la moto de tus sueños. ¡Ahora puedes lucir aquellos guantes de antaño que tanto admirabas! ',
        'texto_seo': 'Si quieres dar un giro especial a tu look de conductor, al aspecto de tu coche o a la apariencia de tu moto, no dejes de revisar nuestro stock Vintage para autos y motos. Aquí encontrarás sorprendentes accesorios Vintage que te harán sentir que viajas en el tiempo. Cuidar tu look de conductor es imprescindible durante tu aventura de carretera. Es por eso que nuestra tienda de productos Vintage te reserva atractivos accesorios. Aquí esperan por ti guantes, chamarras de cuero, gafas de protección, calzados de resistencia, cascos, y muchos otros artículos Vintage para que luzcas una atractiva imagen retro en carretera. No olvides que el uso de los medios de transporte y la imagen que proyectas es él, no solo es exclusivo de su función. También se ha convertido en un símbolo de moda y glamour. ¡Sácale provecho al estilo Vintage!',
        'descripcion_breve': 'Decora tu medio de transporte con accesorios Vintage y luce una atractiva imagen retro durante de tu viaje.',
    },
    {
        'nombre': 'Equipaje',
        'descripcion': 'Contar con el equipaje perfecto para moverte es tan importante como el viaje que harás. Acá en nuestra tienda de productos Vintage contamos con una sección específica para el equipaje. El sitio que nunca imaginaste, y en donde podrás escoger entre mochilas, maletas, billeteras, monederos y más, todos ellos con un fascinante estilo retro.',
        'texto_seo': 'Poseer una mochila o maleta de viaje es de utilidad incuestionable, pero… ¿No te gustaría tener más de una? La calidad de las opciones de equipaje Vintage de nuestra página de ventas es superior a muchas de las valijas de viaje de la actualidad. Resaltan por su confortabilidad y la cómoda repartición de sus divisiones. Algo que facilita una mejor distribución de los objetos en su interior, y por tanto, la mejor organización del contenido. Con nuestras útiles mochilas y maletines Vintage te será muy fácil trasladarte. Sus comodidades las convierten en excelentes opciones para realizar viajes, ir a entrenar, salidas al campo e incluso para fines escolares. Una persona como tú, tan especial, se merece un equipaje exclusivo. ¡Regálate una de nuestras mochilas o maletas Vintage!',
        'descripcion_breve': 'Hazte de una mochila o un maletín confortable. Consigue que el estilo Vintage también forme parte de tu equipaje.',
    },
    {
        'nombre': 'Productos para mascotas',
        'descripcion': '¿Eres amante de los animales?, Esta sección de productos Vintage contiene accesorios increíbles para regalarle a tu querida mascota. Aquí encontrarás numerosos artículos con los que podrás hacer feliz a tu amigo de cuatro patas. Decide entre una bandeja para gatos, ropa de invierno para tu perro, chaqueta vaquera con capucha y otras inimaginables opciones.',
        'texto_seo': 'Una mascota es una figura especial en el hogar. Es en ellas donde nos refugiamos cuando buscamos ternura y de quienes recibimos las más agradables muestras de cariño. ¿Acaso no se merecen un regalo original? Los artículos para mascotas de nuestra tienda de productos Vintage le ofrecerán a tu querido amigo la calidez y confortabilidad que tanto se merece. Harás que se sientan especiales, y lo que es mejor, incluirás en su diario ese toque retro que a tantos nos gusta disfrutar. No te limites, deja que tu amigo también disfrute de la moda Vintage. Obséquiale accesorios que aún siguen siendo útiles y contribuye a que su tiempo junto a ti sea el mejor. No debes olvidar que vivirá menos que tú, ¡Así que no dejes de consentirlo!',
        'descripcion_breve': 'Obsequia a tu mascota útiles accesorios Vintage. Lleva a tu casa artículos que hagan sentir especial a tu amigo peludo',
    },
    {
        'nombre': 'Bebés',
        'descripcion': '¿Esperas un bebé o ya tienes uno?, En nuestra sección para Bebés encontrarás todo tipo de accesorios Vintage que podrás utilizar para el decorado del cuarto de tu pequeñín. Será una oportunidad especial para adquirir muchos de los accesorios que se utilizaron años atrás y que difícilmente puedas adquirir en las tiendas de ahora.',
        'texto_seo': 'No existe momento más hermoso que la espera de un bebé. Una experiencia que difícilmente supere cualquier vivencia conocida. Así sin más comienzan las ansias por comprar objetos especiales a esa personita que tanto deseas, sin embargo, es posible que las opciones que veas queden muy lejos de tus expectativas, ¿Por qué no empezar por accesorios Vintage para bebé? La mayoría de los accesorios Vintage para bebé fueron desarrollados de manera cuidadosa. En su utilización fueron utilizados materiales suaves y saludables. Sin dejar mencionar la originalidad de sus diseños y la confortabilidad ofrecida por los mismos. Por lo que además de brindarle una apariencia retro al cuarto de tu bebé, también te ofrecerán excelentes prestaciones. Busca en nuestra sección de accesorios Vintage para Bebé el objeto especial que tanto andas buscando. Aquí encontrarás cesta para pañales, baberos, peluches y muchos otros artículos Vintage para regalar a tu bebé o decorar su cuarto.',
        'descripcion_breve': 'Decora el cuarto de tu bebé con accesorios Vintage. Consigue que tu bebé aprenda a amar lo retro desde pequeño.',
    },
]