# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-01 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_title', models.CharField(blank=True, max_length=32, null=True, verbose_name='Título de la pestaña')),
                ('page_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Título de la página')),
            ],
            options={
                'verbose_name_plural': 'Páginas Principales',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=64, null=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=64, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.AddField(
            model_name='index',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Proyecto'),
        ),
    ]
