# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-01 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='en_uso',
            field=models.BooleanField(default=False, verbose_name='En uso'),
        ),
    ]
