# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-01 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_proyecto_urls_productos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name_plural': 'Páginas de Inicio'},
        ),
        migrations.AddField(
            model_name='index',
            name='page_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la página'),
        ),
    ]
