# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-03 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190101_2117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='Descuento',
        ),
        migrations.AlterModelOptions(
            name='descuento',
            options={'verbose_name_plural': 'Páginas de descuentos (rebajas)'},
        ),
    ]
