# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-03 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190103_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mejor_Valorado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_title', models.CharField(blank=True, max_length=32, null=True, verbose_name='Título de la pestaña')),
                ('page_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Título de la página')),
                ('page_description', models.TextField(blank=True, null=True, verbose_name='Descripción de la página')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Proyecto')),
            ],
            options={
                'verbose_name_plural': 'Páginas de mejor valorados',
            },
        ),
    ]
