# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-09 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True, verbose_name='Nombre')),
                ('base_url', models.CharField(max_length=255, unique=True, verbose_name='Base URL')),
            ],
            options={
                'verbose_name_plural': 'API Clients',
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True, verbose_name='App')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='Email')),
                ('api_key', models.CharField(max_length=32, unique=True, verbose_name='API Key')),
                ('max_rate', models.IntegerField(default=3600, verbose_name='Max. conexiones por hora')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('api_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.API_Client')),
            ],
            options={
                'verbose_name_plural': 'Apps',
            },
        ),
    ]
