# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-12 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190209_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_client',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
