# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio')),
                ('url_afiliado', models.URLField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL Amazon')),
                ('url_imagen_principal', models.URLField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL Imagen principal')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Sub_Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, verbose_name='Sub Categoría')),
                ('descripcion', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Descripción')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Sub Categorías',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='sub_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Sub_Categoria'),
        ),
    ]
