# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-25 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20181125_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='url_afiliado',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='URL Amazon'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='url_imagen_principal',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='URL Imagen principal'),
        ),
    ]
