# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-25 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20181125_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Nombre'),
        ),
    ]
