# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-25 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20181125_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ahorro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Ahorro'),
        ),
    ]
