# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-26 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import productos.models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_producto_ahorro'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto_920_614',
            field=models.ImageField(blank=True, null=True, upload_to=productos.models.productos_photos_directory, verbose_name='Foto 920 x 614'),
        ),
    ]
