# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-26 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import productos.models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_producto_foto_920_614'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto_320_320',
            field=models.ImageField(blank=True, null=True, upload_to=productos.models.productos_photos_320_320_directory, verbose_name='Foto 320 x 320'),
        ),
        migrations.AddField(
            model_name='producto',
            name='foto_464_299',
            field=models.ImageField(blank=True, null=True, upload_to=productos.models.productos_photos_464_299_directory, verbose_name='Foto 464 x 299'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto_920_614',
            field=models.ImageField(blank=True, null=True, upload_to=productos.models.productos_photos_920_614_directory, verbose_name='Foto 920 x 614'),
        ),
    ]
