# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-26 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_auto_20181126_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='url_amigable',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL amigable'),
        ),
    ]
