# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-26 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_producto_url_amigable'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='url_amigable',
            field=models.SlugField(blank=True, max_length=512, null=True, verbose_name='URL amigable'),
        ),
        migrations.AddField(
            model_name='sub_categoria',
            name='url_amigable',
            field=models.SlugField(blank=True, max_length=512, null=True, verbose_name='URL amigable'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='url_amigable',
            field=models.SlugField(blank=True, max_length=512, null=True, verbose_name='URL amigable'),
        ),
    ]
