# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-26 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_auto_20181126_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ahorro',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='ahorro_euros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ahorro Euros'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ahorro_porciento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ahorro en %'),
        ),
        migrations.AddField(
            model_name='producto',
            name='asin',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='ASIN'),
        ),
        migrations.AddField(
            model_name='producto',
            name='evaluacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Evaluación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='opiniones',
            field=models.IntegerField(blank=True, null=True, verbose_name='Opiniones'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_antes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio Antes'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio Final'),
        ),
    ]
