# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-01 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_proyecto_en_uso'),
        ('productos', '0015_auto_20181227_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='proyecto',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Proyecto'),
        ),
    ]
