# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-02 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_remove_producto_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre_corto',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombre cort'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.TextField(max_length=4096, verbose_name='Nombre'),
        ),
    ]
