# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-12 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0022_auto_20190206_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='texto_seo',
            field=models.TextField(blank=True, null=True, verbose_name='Texto SEO'),
        ),
    ]
