# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-13 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0023_categoria_texto_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='asin',
            field=models.CharField(default=123456, max_length=16, unique=True, verbose_name='ASIN'),
            preserve_default=False,
        ),
    ]
