# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-17 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0024_auto_20190213_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion_breve',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Descripción breve'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre_corto',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombre corto'),
        ),
    ]
